services:
  magic:
    image: mageai/mageai:${MAGE_VERSION}
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    container_name: mageai-${DOCKER_ENVIRONNEMENT}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - ${MAGEAI_PORT}:6789
    volumes:
      - .:/home/src/
      - ../${MAGE_DATA:/home/src/${MAGE_DATA}
      - ../${PROJECT_NAME}:/home/src/${PROJECT_NAME}
    restart: on-failure:5

  copy_data:
    image: alpine:latest
    container_name: copy_data-${DOCKER_ENVIRONNEMENT}
    volumes:
      - ./${PROJECT_NAME}:/src/${PROJECT_NAME}
      - ./${MAGE_DATA}:/src/${MAGE_DATA}
      - ../${PROJECT_NAME}:/dest/${PROJECT_NAME}
      - ../${MAGE_DATA}:/dest/${MAGE_DATA}
    entrypoint: /bin/sh -c "cp -r /src/${PROJECT_NAME}/* /dest/${PROJECT_NAME}/ && cp -r /src/${MAGE_DATA}/* /dest/${MAGE_DATA}/"
